import Navbar from '../components/Navbar'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'
//import { Space_Grotesk } from 'next/font/google'

const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
        <div className="grid place-content-center min-h-screen bg-amber-100 p-4">
          <div className="sm:w-[500px] md:w-[600px] lg:w-[700px]">
            <Navbar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
